-- =============================================================================
-- SOVEREIGN BRIEF — Supabase Schema (실측 확정본 2026-05-05)
-- Supabase 대시보드 + 인덱스 쿼리 기반. 참조용 DDL입니다.
-- 실제 운영 DB에 재실행하지 마세요 (데이터 손실 위험).
-- =============================================================================


-- =============================================================================
-- 1. 신호 기록
-- 작성: scripts/fill_signal_outcomes.py, src/morning_brief/signal_logger.py
-- RLS: ON (정책 미확인)
-- =============================================================================

CREATE TABLE IF NOT EXISTS signal_log (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_date      DATE        NOT NULL UNIQUE,
    regime_state     TEXT        NOT NULL,   -- BullQuiet / BullHeated / BearPanic / Choppy / Transitional
    vol_level        TEXT        NOT NULL,   -- High / Mid / Low
    vol_trend        TEXT,                   -- rising / falling / stable
    overlay_decision TEXT        NOT NULL,   -- promote / research_only
    confidence       TEXT,                   -- HIGH / MEDIUM / null
    reasons          JSONB,                  -- ["vol_regime_v2_promoted", ...]
    btc_price_open   NUMERIC,
    btc_price_7d     NUMERIC,               -- fill_signal_outcomes.py 자동 채움
    ret_7d           NUMERIC,               -- (price_7d / price_open) - 1
    hit              BOOLEAN,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);


-- =============================================================================
-- 2. 구독 관리
-- 작성: frontend/lib/subscriptions/repository.ts (Cloudflare Pages Functions)
-- 읽기: src/morning_brief/subscriptions/supabase_repository.py (브리핑 발송)
-- RLS: ON (정책 미확인)
-- =============================================================================

CREATE TABLE IF NOT EXISTS subscriptions (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email            TEXT        NOT NULL,
    email_normalized TEXT        NOT NULL,
    newsletter       TEXT        NOT NULL,   -- 'morning-brief'
    status           TEXT        NOT NULL,   -- pending / active / unsubscribed / bounced
    status_reason    TEXT,                   -- awaiting_confirmation / confirmed / user_unsubscribed
    subscribed_at    TIMESTAMPTZ,
    unsubscribed_at  TIMESTAMPTZ,
    bounced_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX subscriptions_newsletter_email_normalized_idx
    ON subscriptions (newsletter, email_normalized);

CREATE INDEX subscriptions_status_idx
    ON subscriptions (newsletter, status);   -- list_active_recipients 쿼리용


CREATE TABLE IF NOT EXISTS subscription_tokens (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    subscriber_id   UUID        NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    token_type      TEXT        NOT NULL,   -- 'confirm_subscription'
    token_hash      TEXT        NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    consumed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX subscription_tokens_lookup_idx
    ON subscription_tokens (token_type, token_hash);   -- findConfirmationToken 쿼리용


-- =============================================================================
-- 3. 메일 발송 이벤트 로그
-- 현재 레코드 없음 — 코드에서 직접 write하는 경로 미확인 (예약 테이블로 추정)
-- RLS: ON (정책 미확인)
-- =============================================================================

CREATE TABLE IF NOT EXISTS mail_events (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    subscriber_id   UUID        REFERENCES subscriptions(id),
    email           TEXT        NOT NULL,
    mail_type       TEXT        NOT NULL,
    status          TEXT        NOT NULL,
    provider        TEXT        NOT NULL,
    error_code      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =============================================================================
-- 4. BTC 선물 일별 데이터
-- 작성: scripts/backfill_btc_futures.py
--        src/morning_brief/analysis/sentiment_join/sources/futures.py (일별 upsert)
-- RLS: OFF
-- =============================================================================

CREATE TABLE IF NOT EXISTS btc_futures_daily (
    date                 DATE             NOT NULL,
    symbol               TEXT             NOT NULL DEFAULT 'BTCUSDT',
    funding_rate         DOUBLE PRECISION,
    open_interest_usd    DOUBLE PRECISION,
    btc_long_short_ratio DOUBLE PRECISION,
    source               TEXT             NOT NULL DEFAULT 'binance',
    created_at           TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    PRIMARY KEY (date, symbol)
);


-- =============================================================================
-- 5. 스테이블코인 공급량 일별 데이터
-- 작성: scripts/backfill_stablecoin_supply.py
--        src/morning_brief/analysis/sentiment_join/sources/defillama_stablecoins.py
-- RLS: ON (정책 미확인)
-- =============================================================================

CREATE TABLE IF NOT EXISTS stablecoin_supply_daily (
    date        DATE             NOT NULL,
    symbol      TEXT             NOT NULL,   -- USDT / USDC
    supply_usd  DOUBLE PRECISION NOT NULL,
    source      TEXT             NOT NULL DEFAULT 'defillama',
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    PRIMARY KEY (date, symbol)
);


-- =============================================================================
-- 6. BTC ETF 데이터 레이어
-- 작성: src/morning_brief/data/etf_storage.py
-- Silver:    필드별 정규화 레코드 (ELT)
-- Gold:      티커별 집계 레코드 (공식 소스), PK = (ticker, as_of_date)
-- Reference: 집계 레코드 (aggregator / reference_only), UNIQUE = (ticker, as_of_date, source_type), PK 없음
-- Bronze:    Supabase Storage 버킷 'btc-etf-bronze' (테이블 아님)
--            경로 패턴: {ticker}/{YYYYMMDD}/{run_id}-{checksum[:12]}.{format}
-- RLS: OFF (3개 테이블 모두)
-- =============================================================================

-- 6-1. btc_etf_silver — PK 없음, UNIQUE = (ticker, as_of_date, field_name, source_type)
CREATE TABLE IF NOT EXISTS btc_etf_silver (
    run_id             TEXT        NOT NULL,
    ticker             TEXT        NOT NULL,
    issuer             TEXT        NOT NULL,
    field_name         TEXT        NOT NULL,
    field_value        JSONB,
    value_type         TEXT        NOT NULL,   -- null / bool / int / float / str
    unit               TEXT,
    as_of_date         DATE        NOT NULL,
    collected_at       TIMESTAMPTZ NOT NULL,
    source_url         TEXT        NOT NULL,
    source_type        TEXT        NOT NULL,   -- official_html / official_json / official_csv / aggregator
    source_format      TEXT        NOT NULL,
    parse_method       TEXT        NOT NULL,
    source_file_url    TEXT,
    quality_status     TEXT        NOT NULL,   -- ok / degraded / critical
    raw_label          TEXT,
    raw_text           TEXT,
    schema_version     TEXT        NOT NULL DEFAULT 'v1',
    bronze_object_path TEXT
);

CREATE UNIQUE INDEX btc_etf_silver_unique
    ON btc_etf_silver (ticker, as_of_date, field_name, source_type);

CREATE INDEX idx_btc_etf_silver_as_of_date
    ON btc_etf_silver (as_of_date);

CREATE INDEX idx_btc_etf_silver_ticker_as_of_date
    ON btc_etf_silver (ticker, as_of_date);


-- 6-2. btc_etf_gold — PK = (ticker, as_of_date)
-- extra_fields(ETF 발행사별 추가 필드)가 개별 컬럼으로 확장됨
CREATE TABLE IF NOT EXISTS btc_etf_gold (
    run_id                  TEXT            NOT NULL,
    schema_version          TEXT            NOT NULL DEFAULT 'v1',
    ticker                  TEXT            NOT NULL,
    issuer                  TEXT,
    source_url              TEXT,
    as_of_date              DATE            NOT NULL,
    collected_at            TIMESTAMPTZ     NOT NULL,
    source_type             TEXT,
    quality_status          TEXT            NOT NULL DEFAULT 'ok',
    aum_usd                 DOUBLE PRECISION,
    shares_outstanding      BIGINT,
    total_btc               DOUBLE PRECISION,
    bitcoin_per_share       DOUBLE PRECISION,
    daily_volume            BIGINT,
    bronze_object_path      TEXT,
    -- extra_fields (ETF 발행사별)
    basket_bitcoin_amount   DOUBLE PRECISION,
    estimated_total_btc     DOUBLE PRECISION,
    premium_discount_pct    DOUBLE PRECISION,
    primary_exchange        TEXT,
    nav_per_share           DOUBLE PRECISION,
    market_price            DOUBLE PRECISION,
    gaap_aum                DOUBLE PRECISION,
    gaap_nav_per_share      DOUBLE PRECISION,
    bid_ask_spread_30d      DOUBLE PRECISION,
    sponsor_fee             DOUBLE PRECISION,
    bitcoin_reserve_btc     DOUBLE PRECISION,
    trust_net_assets_btc    DOUBLE PRECISION,
    bitcoin_in_trust        DOUBLE PRECISION,
    net_assets_aum          DOUBLE PRECISION,
    aum_non_gaap            DOUBLE PRECISION,
    total_bitcoin_in_trust  DOUBLE PRECISION,
    PRIMARY KEY (ticker, as_of_date)
);

CREATE INDEX idx_btc_etf_gold_as_of_date
    ON btc_etf_gold (as_of_date);

CREATE INDEX idx_btc_etf_gold_ticker_as_of_date
    ON btc_etf_gold (ticker, as_of_date);


-- 6-3. btc_etf_reference — PK 없음, UNIQUE = (ticker, as_of_date, source_type)
CREATE TABLE IF NOT EXISTS btc_etf_reference (
    run_id                  TEXT            NOT NULL,
    schema_version          TEXT            NOT NULL DEFAULT 'v1',
    ticker                  TEXT            NOT NULL,
    issuer                  TEXT,
    source_url              TEXT,
    as_of_date              DATE            NOT NULL,
    collected_at            TIMESTAMPTZ     NOT NULL,
    source_type             TEXT            NOT NULL,
    quality_status          TEXT            NOT NULL DEFAULT 'ok',
    aum_usd                 DOUBLE PRECISION,
    shares_outstanding      BIGINT,
    total_btc               DOUBLE PRECISION,
    bitcoin_per_share       DOUBLE PRECISION,
    daily_volume            BIGINT,
    bronze_object_path      TEXT,
    basket_bitcoin_amount   DOUBLE PRECISION,
    estimated_total_btc     DOUBLE PRECISION,
    premium_discount_pct    DOUBLE PRECISION,
    primary_exchange        TEXT,
    nav_per_share           DOUBLE PRECISION,
    market_price            DOUBLE PRECISION,
    gaap_aum                DOUBLE PRECISION,
    gaap_nav_per_share      DOUBLE PRECISION,
    bid_ask_spread_30d      DOUBLE PRECISION,
    sponsor_fee             DOUBLE PRECISION,
    bitcoin_reserve_btc     DOUBLE PRECISION,
    trust_net_assets_btc    DOUBLE PRECISION,
    bitcoin_in_trust        DOUBLE PRECISION,
    net_assets_aum          DOUBLE PRECISION,
    aum_non_gaap            DOUBLE PRECISION,
    total_bitcoin_in_trust  DOUBLE PRECISION
);

CREATE UNIQUE INDEX btc_etf_reference_unique
    ON btc_etf_reference (ticker, as_of_date, source_type);

CREATE INDEX idx_btc_etf_reference_as_of_date
    ON btc_etf_reference (as_of_date);

CREATE INDEX idx_btc_etf_reference_ticker_as_of_date
    ON btc_etf_reference (ticker, as_of_date);


-- =============================================================================
-- RLS 정책 현황
-- =============================================================================
-- pg_policies 조회 결과 정책 없음 (No rows returned).
-- RLS ON + 정책 없음 = service_role 키만 접근 가능, anon/authenticated 차단.
-- 파이프라인과 Pages Functions 모두 service_role 키 사용 → 현재 정상 동작.
--
-- btc_etf_gold / btc_etf_reference / btc_etf_silver 는 RLS OFF →
-- anon 키로도 읽기·쓰기 가능한 상태. 현재는 내부 파이프라인만 write하므로
-- 실질적 위험은 낮으나, 필요 시 RLS 활성화 검토 필요.
